services:
  python_image:
    build: .
    container_name: python_image
    volumes:
      - .:/app
    working_dir: /app
    entrypoint: ["sleep", "infinity"]
    ports:
      - "8001:8001"
  postgres:
    image: postgres:16.0-alpine
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "root" ]
      timeout: 45s
      interval: 10s
      retries: 10
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
    volumes:
      - ./scripts/db:/docker-entrypoint-initdb.d/
